CREATE OR REPLACE FUNCTION exec (sql TEXT) RETURNS VOID AS $$
BEGIN
  EXECUTE sql;
END
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION exec_sql (sql TEXT) RETURNS TABLE (result TEXT) AS $$
BEGIN
  RETURN QUERY EXECUTE sql;
END
$$ LANGUAGE plpgsql;
